name: Build and deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # TODO: use this to check for broken links in docs/ ?
      #- name: Check for dead links in Markdown
      #  uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
      - name: Build site
        run: nix-shell --pure --command 'make publish'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: output
